[server]
host="localhost"
port=8081
allow_origins=true
#origins=["*"]
methods=["*"]
headers=["*"]
allow_credentials=true
allow_wildcard=true
allow_websockets=true
[logging]
human_readable=true
level="debug"
[session]
timeout=30 # time in seconds
[postgres]
host="localhost"
port=5432
username="postgres"
password="postgres"
database="postgres"
driver="pgx"