[server]
host="localhost"
port=8081
allow_origins=true
#origins=["*"]
methods=["*"]
headers=["*"]
allow_credentials=true
allow_wildcard=true
allow_websockets=true
[logging]
human_readable=true
level="debug"